### ISSUE TITLE
Question about language [tokenizer] and [encoder] 

### ISSUE THREAD

**Issue by YunzeMan** [Open3DA/LL3DA#1]
Thanks for the great work. In you paper the pipeline illustration, you freeze the "Textual Tokenizer" and learn the "Word Embedding". I am wondering what you are using for these two parts. I didn't find the explanation in your paper.

I'm guessing you tokenize the textual inputs with the BERT tokenizer, and finetune a BERT to obtain a word embedding? If so, what models are you exactly utilizing?

**Comment by ch3cook-fdu** [comment]
Hi, the multi-modal transformer is built upon the codebase of InstructBLIP with BERT embedding initialization (both **position** and **word** embedding), while other parameters are initialized randomly. 

In our experiments, we train all parameters in 1) the visual prompt encoder, and 2) the multi-modal transformer, and keep other parts frozen.

LL3DA contains two tokenizers, the LLM tokenizer and BERT tokenizer. The output of BERT tokenizer is fed into the multi-modal transformer, and the output of LLM tokenizer is fed into the LLM backend.

**Comment by YunzeMan** [comment]
Thanks for your prompt explanation. Since you mentioned 
> we train all parameters in 1) the visual prompt encoder, and 2) the multi-modal transformer, and keep other parts frozen.

I find it a little bit counter-ntuitive that you set `Word Embeddings` to "Trainable Parameters" in your Figure 2 illustration. If the tokenizer is frozen, how come the word embedding is learnable rather than deterministic.

**Comment by ch3cook-fdu** [comment]
The word tokenizer in our paper refers to modules that disassemble words into **token IDs**, and generally they don't have any trainable parameters. 

Considering that some language models train their word tokenizers (_i.e._ SentencePiece), we identify our tokenizer as frozen in our paper.
