### ISSUE TITLE
Question about `qformer_input_ids` and `input_ids`

### ISSUE THREAD

**Issue by cocoshe** [Open3DA/LL3DA#17]
Thanks for your great work!

I noticed qformer is using the `qformer_input_ids`, I wanna ask if the `qformer_input_ids` and `input_ids` in `inputs` are the same. What's the relationship between?

**Comment by ch3cook-fdu** [comment]
They are not the same, `qformer_input_ids` are input into the Qformer, while `input_ids` are input into the frozen LLM. Though they represent the same message, they use different embeddings and different tokenizers.

**Comment by cocoshe** [comment]
> They are not the same, `qformer_input_ids` are input into the Qformer, while `input_ids` are input into the frozen LLM. Though they represent the same message, they use different embeddings and different tokenizers.

It means the instructions are the same(e.g. "What is this object?"), and the `qformer_input_ids` is tokenized with the vocabulary based on InstructionBlip, and the `input_ids` is tokenized with the vocabulary based on LLM?

**Comment by ch3cook-fdu** [comment]
Yes, that’s the case.

**Comment by cocoshe** [comment]
> Yes, that’s the case.

OK, Thanks for your reply~
