### ISSUE TITLE
densecap任务

### ISSUE THREAD

**Issue by xjj1999** [Open3DA/LL3DA#24]
请问在训练过程中，作者有碰到对于densecap任务不同的val样例，llm输出个固定格式，内容相似的答案的现象吗

**Comment by ch3cook-fdu** [comment]
I do not quite understand your question, could you provide me with some examples?

**Comment by xjj1999** [comment]
![20240725-185406](https://github.com/user-attachments/assets/44ad1c09-de97-4685-aee2-c419f02d43a2)
比如说训练了几个epoch，验证集的结果如图
=

**Comment by xjj1999** [comment]
![20240725-185406](https://github.com/user-attachments/assets/d2dee914-b5fc-4c56-9077-d7b4cf2413fc)

**Comment by xjj1999** [comment]
比如说训练了10个epoch之后，验证集结果如图，llm对不同问题的输出即response_pred基本一致。这里只截取了部分，几乎整个验证集的输出答案都是这个格式和内容。

**Comment by ch3cook-fdu** [comment]
If you are training with ScanRefer data only, it might be normal.

**Comment by xjj1999** [comment]
谢谢！我确实是只用了scanrefer数据集。我尝试下多数据集联合训练

**Comment by xjj1999** [comment]
May I ask if this phenomenon disappears naturally during joint training on multiple datasets?

**Comment by ch3cook-fdu** [comment]
If you feed diverse data on more tasks, this might be alleviated.

**Comment by xjj1999** [comment]
请问方便提供densecap任务训练过程中验证集的评测指标变化曲线吗？

**Comment by ch3cook-fdu** [comment]
[scanrefer-opt-1.3b-logger.log](https://github.com/user-attachments/files/16459151/scanrefer-opt-1.3b-logger.log)
Here is the log for ScanRefer fine-tuning.

**Comment by xjj1999** [comment]
请问unified_scanrefer是如何实现的，从日志上看batch=16,一个epoch为27504，远大于scanrefer数据集的数据量

**Comment by ch3cook-fdu** [comment]
27504 is the total iterations for 12 epochs.

**Comment by xjj1999** [comment]
感谢！

**Comment by xjj1999** [comment]
还有个问题是从日志上看，模型在一阶段训练时在densecap上就有了不错的性能，请问方便提供一阶段训练时的验证集指标吗？或者说需要大概多少次迭代，模型能具备相关能力。

**Comment by ch3cook-fdu** [comment]
We show the corresponding metrics in Table 5 of our paper. Please follow the pre-training guide provided in Readme.

**Comment by xjj1999** [comment]
感谢回答，问题已经解决了。我想进一步复现补充材料中Open-Vocabulary实验，请问方便提供ovdet微调后的权重吗
