### ISSUE TITLE
How to do inference

### ISSUE THREAD

**Issue by rocksterssby** [Open3DA/LL3DA#29]
Steps i have done:
Until this process using our installation guide

`./facebook/opt-1.3b/
  config.json
  merges.txt
  pytorch_model.bin
  special_tokens_map.json
  tokenizer_config.json
  vocab.json`
  
  
  and i downloaded the pretrained model from the https://huggingface.co/CH3COOK/LL3DA-weight-release/blob/main/ll3da-opt-1.3b.pth
  And i renamed and put it under `LL3DA\ckpts\opt-1.3b\ll3da-generalist\checkpoint.pth`
  
  And i run this command
`  bash scripts/opt-1.3b/eval.scanqa.sh
`  

**i get these results:**

```
Evaluate ; Batch [550/585]; Evaluating on iter: -1; Iter time 3.03; Mem 5624.94MB
Evaluate ; Batch [560/585]; Evaluating on iter: -1; Iter time 3.03; Mem 5624.94MB
Evaluate ; Batch [570/585]; Evaluating on iter: -1; Iter time 3.12; Mem 5624.94MB
Evaluate ; Batch [580/585]; Evaluating on iter: -1; Iter time 2.98; Mem 5624.94MB

----------------------Evaluation-----------------------

[BLEU-1] Mean: 0.3897, Max: 1.0000, Min: 0.0000
[BLEU-2] Mean: 0.2684, Max: 1.0000, Min: 0.0000
[BLEU-3] Mean: 0.1920, Max: 1.0000, Min: 0.0000
[BLEU-4] Mean: 0.1311, Max: 1.0000, Min: 0.0000
[CIDEr] Mean: 0.7535, Max: 10.0000, Min: 0.0000
[ROUGE-L] Mean: 0.3655, Max: 1.0000, Min: 0.0000
[METEOR] Mean: 0.1527, Max: 1.0000, Min: 0.0000
```

And under this folder i get these files
```
LL3DA\ckpts\opt-1.3b\ll3da-generalist
checkpoint.pth
qa_corpus_val.json
qa_pred_gt_val.json
qa_pred_val.json

```
  
So my issue is how can i get this view
  
![image](https://github.com/user-attachments/assets/0f9e27ab-f731-407f-b803-d33b2e033147)

**Comment by rocksterssby** [comment]
can any one give me small guidance how to proceed after this

**Comment by ch3cook-fdu** [comment]
Hi, the gif file you shown is just our teaser image made by PowerPoints, not the interactive interface of our codebase. Our code only generates text outputs.

**Comment by rocksterssby** [comment]
ok thank you so much, i get it
