### ISSUE TITLE
something wrong with training

### ISSUE THREAD

**Issue by kuaileqipaoshui** [Open3DA/LL3DA#6]
File "/data/private/LL3DA/main.py", line 299, in main
do_train(
File "/data/private/LL3DA/engine.py", line 160, in do_train
task_metrics = test_loader.dataset.eval_func(
File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "/data/private/LL3DA/eval_utils/evaluate_qa.py", line 123, in evaluate
outputs = model(model_input, is_eval=True, task_name='qa')
File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
output = self._run_ddp_forward(*inputs, **kwargs)
File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
return module_to_run(*inputs[0], **kwargs[0])
File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "/data/private/LL3DA/models/model_general.py", line 56, in forward
outputs = self.captioner(
File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "/data/private/LL3DA/models/ll3da/captioner.py", line 300, in forward
return self.predict_answer(detector_output, inputs, max_gen_length=max_gen_length)
File "/data/private/LL3DA/models/ll3da/captioner.py", line 441, in predict_answer
output = generation(
File "/data/private/LL3DA/models/ll3da/generation_utils.py", line 212, in generation
outputs = beam_search_decode(transformer, **kwargs)
File "/data/private/LL3DA/models/ll3da/generation_utils.py", line 156, in beam_search_decode
output_ids = torch.cat([
File "/data/private/LL3DA/models/ll3da/generation_utils.py", line 158, in
[
File "/data/private/LL3DA/models/ll3da/generation_utils.py", line 159, in
beam_sentence.unsqueeze(0)
AttributeError: 'NoneType' object has no attribute 'unsqueeze'

**Comment by ch3cook-fdu** [comment]
Can you show me the output of https://github.com/Open3DA/LL3DA/blob/main/models/ll3da/captioner.py#L443C31-L449C18 ?

**Comment by kuaileqipaoshui** [comment]
> Can you show me the output of https://github.com/Open3DA/LL3DA/blob/main/models/ll3da/captioner.py#L443C31-L449C18 ?

How should I show you the output? What should I do?

**Comment by ch3cook-fdu** [comment]
Please check whether the generation argument: `max_length` equals to `0`? Have you done any modifications to the code? The training process seems fine with me.

**Comment by kuaileqipaoshui** [comment]
> Please check whether the generation argument: `max_length` equals to `0`? Have you done any modifications to the code? The training process seems fine with me.

No, I don't modify anything. And it is working fine before this.
![ll3da3](https://github.com/Open3DA/LL3DA/assets/137666741/27138a6a-97ae-4561-b572-7aa19e569c59)

**Comment by ch3cook-fdu** [comment]
It seems like the error occurs at the last iteration. Please check the value of `model_inputs` at https://github.com/Open3DA/LL3DA/blob/main/eval_utils/evaluate_qa.py#L118-L121 and the `sample_instruction`  at https://github.com/Open3DA/LL3DA/blob/main/models/ll3da/captioner.py#L438

**Comment by kuaileqipaoshui** [comment]
> It seems like the error occurs at the last iteration. Please check the value of `model_inputs` at https://github.com/Open3DA/LL3DA/blob/main/eval_utils/evaluate_qa.py#L118-L121 and the `sample_instruction` at https://github.com/Open3DA/LL3DA/blob/main/models/ll3da/captioner.py#L438

I still haven't found a solution. The evaluate on unified_3dllm_scene_description,unified_3dllm_embodied_dialogue,unified_3dllm_embodied_planning,unified_scanqa is fine.
![ll3da4](https://github.com/Open3DA/LL3DA/assets/137666741/ef9074db-58b0-44d4-a14c-568347720db4)

But an error occurred while evaluating unified_scanqa. Are they any different?

**Comment by kuaileqipaoshui** [comment]
> It seems like the error occurs at the last iteration. Please check the value of `model_inputs` at https://github.com/Open3DA/LL3DA/blob/main/eval_utils/evaluate_qa.py#L118-L121 and the `sample_instruction` at https://github.com/Open3DA/LL3DA/blob/main/models/ll3da/captioner.py#L438

I still haven't found a solution. The evaluate on unified_3dllm_scene_description,unified_3dllm_embodied_dialogue,unified_3dllm_embodied_planning,unified_scanqa is fine.

But an error occurred while evaluating unified_scanqa. Are they any different?
The only thing I changed : Because I lack scannet's data for a scene, I delete it first in scanqa's json file. Does this matter?

**Comment by kuaileqipaoshui** [comment]
> It seems like the error occurs at the last iteration. Please check the value of `model_inputs` at https://github.com/Open3DA/LL3DA/blob/main/eval_utils/evaluate_qa.py#L118-L121 and the `sample_instruction` at https://github.com/Open3DA/LL3DA/blob/main/models/ll3da/captioner.py#L438

I still haven't found a solution. The evaluate on unified_3dllm_scene_description,unified_3dllm_embodied_dialogue,unified_3dllm_embodied_planning,unified_scanqa is fine.

![ll3da4](https://github.com/Open3DA/LL3DA/assets/137666741/b6a71d87-a473-4520-baa3-7486b02bcde3)


But an error occurred while evaluating unified_scanqa. Are they any different?
The only thing I changed : Because I lack scannet's data for a scene, I delete it first in scanqa's json file. Does this matter?

**Comment by ch3cook-fdu** [comment]
This could be a problem. I recommend you to train with full data. If you wish to train on partial of the data, please make sure all annotations related to the missing scenes are deleted.

**Comment by kuaileqipaoshui** [comment]
> This could be a problem. I recommend you to train with full data. If you wish to train on partial of the data, please make sure all annotations related to the missing scenes are deleted.

When I train with full data, I find the training log :
Epoch [2/32]; Iter [11990/127936]; Loss 1.51; LR 9.79e-05; Iter time 0.46; ETA 14:48:34; Mem 18615.49MB
Loss in not finite. Skip this training step.
Loss in not finite. Skip this training step.
Loss in not finite. Skip this training step.
Loss in not finite. Skip this training step.
Loss in not finite. Skip this training step.
Loss in not finite. Skip this training step.
Loss in not finite. Skip this training step.
Loss in not finite. Skip this training step.
Epoch [3/32]; Iter [12000/127936]; Loss 1.51; LR 9.79e-05; Iter time 0.48; ETA 15:23:59; Mem 18615.49MB

What happened?

**Comment by gaohan-cmd** [comment]
> > Please check whether the generation argument: `max_length` equals to `0`? Have you done any modifications to the code? The training process seems fine with me.
> 
> No, I don't modify anything. And it is working fine before this. ![ll3da3](https://private-user-images.githubusercontent.com/137666741/311735783-27138a6a-97ae-4561-b572-7aa19e569c59.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyODMzMjksIm5iZiI6MTcxNDI4MzAyOSwicGF0aCI6Ii8xMzc2NjY3NDEvMzExNzM1NzgzLTI3MTM4YTZhLTk3YWUtNDU2MS1iNTcyLTdhYTE5ZTU2OWM1OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQwNTQzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGE4ZGYyMzUwY2E2OGU5ZWJmN2E1ZmRhZmE1ZWQ4MmZkMmI4MTkyYjM2NWUwYzYwN2EyNGVhYzFjMDAyZmUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EPynhFDpabU-nWPROLDk0wNkeNmm-SSW4BeXfAieyoo)

Hello, may I ask if the log above the screenshot is from running train.generalist.sh? Have you modified the parameters inside scripts/opt-1.3b/train.generalist.sh?
